/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace SavariWala
{
  public enum ErrorCode
  {
    Unspecified = 0,
    UserNotFound = 1,
    InvalidArg = 2,
    Interrupted = 3,
  }
}
