/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace SavariWala
{
  public partial class RequestHandler {
    public interface Iface {
      long submitBooking(BookingParams bookingParams);
      #if SILVERLIGHT
      IAsyncResult Begin_submitBooking(AsyncCallback callback, object state, BookingParams bookingParams);
      long End_submitBooking(IAsyncResult asyncResult);
      #endif
      BookingMatchResults matchBooking(SavariWala.GeoLoc src);
      #if SILVERLIGHT
      IAsyncResult Begin_matchBooking(AsyncCallback callback, object state, SavariWala.GeoLoc src);
      BookingMatchResults End_matchBooking(IAsyncResult asyncResult);
      #endif
      BookingMatchResults matchAndFilterBooking(SavariWala.GeoLoc src, SavariWala.GeoLoc dst);
      #if SILVERLIGHT
      IAsyncResult Begin_matchAndFilterBooking(AsyncCallback callback, object state, SavariWala.GeoLoc src, SavariWala.GeoLoc dst);
      BookingMatchResults End_matchAndFilterBooking(IAsyncResult asyncResult);
      #endif
      List<PooledBooking> fetchResults(int id, int count);
      #if SILVERLIGHT
      IAsyncResult Begin_fetchResults(AsyncCallback callback, object state, int id, int count);
      List<PooledBooking> End_fetchResults(IAsyncResult asyncResult);
      #endif
      bool cancel(long bookingId);
      #if SILVERLIGHT
      IAsyncResult Begin_cancel(AsyncCallback callback, object state, long bookingId);
      bool End_cancel(IAsyncResult asyncResult);
      #endif
    }

    public class Client : IDisposable, Iface {
      public Client(TProtocol prot) : this(prot, prot)
      {
      }

      public Client(TProtocol iprot, TProtocol oprot)
      {
        iprot_ = iprot;
        oprot_ = oprot;
      }

      protected TProtocol iprot_;
      protected TProtocol oprot_;
      protected int seqid_;

      public TProtocol InputProtocol
      {
        get { return iprot_; }
      }
      public TProtocol OutputProtocol
      {
        get { return oprot_; }
      }


      #region " IDisposable Support "
      private bool _IsDisposed;

      // IDisposable
      public void Dispose()
      {
        Dispose(true);
      }
      

      protected virtual void Dispose(bool disposing)
      {
        if (!_IsDisposed)
        {
          if (disposing)
          {
            if (iprot_ != null)
            {
              ((IDisposable)iprot_).Dispose();
            }
            if (oprot_ != null)
            {
              ((IDisposable)oprot_).Dispose();
            }
          }
        }
        _IsDisposed = true;
      }
      #endregion


      
      #if SILVERLIGHT
      public IAsyncResult Begin_submitBooking(AsyncCallback callback, object state, BookingParams bookingParams)
      {
        return send_submitBooking(callback, state, bookingParams);
      }

      public long End_submitBooking(IAsyncResult asyncResult)
      {
        oprot_.Transport.EndFlush(asyncResult);
        return recv_submitBooking();
      }

      #endif

      public long submitBooking(BookingParams bookingParams)
      {
        #if !SILVERLIGHT
        send_submitBooking(bookingParams);
        return recv_submitBooking();

        #else
        var asyncResult = Begin_submitBooking(null, null, bookingParams);
        return End_submitBooking(asyncResult);

        #endif
      }
      #if SILVERLIGHT
      public IAsyncResult send_submitBooking(AsyncCallback callback, object state, BookingParams bookingParams)
      #else
      public void send_submitBooking(BookingParams bookingParams)
      #endif
      {
        oprot_.WriteMessageBegin(new TMessage("submitBooking", TMessageType.Call, seqid_));
        submitBooking_args args = new submitBooking_args();
        args.BookingParams = bookingParams;
        args.Write(oprot_);
        oprot_.WriteMessageEnd();
        #if SILVERLIGHT
        return oprot_.Transport.BeginFlush(callback, state);
        #else
        oprot_.Transport.Flush();
        #endif
      }

      public long recv_submitBooking()
      {
        TMessage msg = iprot_.ReadMessageBegin();
        if (msg.Type == TMessageType.Exception) {
          TApplicationException x = TApplicationException.Read(iprot_);
          iprot_.ReadMessageEnd();
          throw x;
        }
        submitBooking_result result = new submitBooking_result();
        result.Read(iprot_);
        iprot_.ReadMessageEnd();
        if (result.__isset.success) {
          return result.Success;
        }
        if (result.__isset.err) {
          throw result.Err;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "submitBooking failed: unknown result");
      }

      
      #if SILVERLIGHT
      public IAsyncResult Begin_matchBooking(AsyncCallback callback, object state, SavariWala.GeoLoc src)
      {
        return send_matchBooking(callback, state, src);
      }

      public BookingMatchResults End_matchBooking(IAsyncResult asyncResult)
      {
        oprot_.Transport.EndFlush(asyncResult);
        return recv_matchBooking();
      }

      #endif

      public BookingMatchResults matchBooking(SavariWala.GeoLoc src)
      {
        #if !SILVERLIGHT
        send_matchBooking(src);
        return recv_matchBooking();

        #else
        var asyncResult = Begin_matchBooking(null, null, src);
        return End_matchBooking(asyncResult);

        #endif
      }
      #if SILVERLIGHT
      public IAsyncResult send_matchBooking(AsyncCallback callback, object state, SavariWala.GeoLoc src)
      #else
      public void send_matchBooking(SavariWala.GeoLoc src)
      #endif
      {
        oprot_.WriteMessageBegin(new TMessage("matchBooking", TMessageType.Call, seqid_));
        matchBooking_args args = new matchBooking_args();
        args.Src = src;
        args.Write(oprot_);
        oprot_.WriteMessageEnd();
        #if SILVERLIGHT
        return oprot_.Transport.BeginFlush(callback, state);
        #else
        oprot_.Transport.Flush();
        #endif
      }

      public BookingMatchResults recv_matchBooking()
      {
        TMessage msg = iprot_.ReadMessageBegin();
        if (msg.Type == TMessageType.Exception) {
          TApplicationException x = TApplicationException.Read(iprot_);
          iprot_.ReadMessageEnd();
          throw x;
        }
        matchBooking_result result = new matchBooking_result();
        result.Read(iprot_);
        iprot_.ReadMessageEnd();
        if (result.__isset.success) {
          return result.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "matchBooking failed: unknown result");
      }

      
      #if SILVERLIGHT
      public IAsyncResult Begin_matchAndFilterBooking(AsyncCallback callback, object state, SavariWala.GeoLoc src, SavariWala.GeoLoc dst)
      {
        return send_matchAndFilterBooking(callback, state, src, dst);
      }

      public BookingMatchResults End_matchAndFilterBooking(IAsyncResult asyncResult)
      {
        oprot_.Transport.EndFlush(asyncResult);
        return recv_matchAndFilterBooking();
      }

      #endif

      public BookingMatchResults matchAndFilterBooking(SavariWala.GeoLoc src, SavariWala.GeoLoc dst)
      {
        #if !SILVERLIGHT
        send_matchAndFilterBooking(src, dst);
        return recv_matchAndFilterBooking();

        #else
        var asyncResult = Begin_matchAndFilterBooking(null, null, src, dst);
        return End_matchAndFilterBooking(asyncResult);

        #endif
      }
      #if SILVERLIGHT
      public IAsyncResult send_matchAndFilterBooking(AsyncCallback callback, object state, SavariWala.GeoLoc src, SavariWala.GeoLoc dst)
      #else
      public void send_matchAndFilterBooking(SavariWala.GeoLoc src, SavariWala.GeoLoc dst)
      #endif
      {
        oprot_.WriteMessageBegin(new TMessage("matchAndFilterBooking", TMessageType.Call, seqid_));
        matchAndFilterBooking_args args = new matchAndFilterBooking_args();
        args.Src = src;
        args.Dst = dst;
        args.Write(oprot_);
        oprot_.WriteMessageEnd();
        #if SILVERLIGHT
        return oprot_.Transport.BeginFlush(callback, state);
        #else
        oprot_.Transport.Flush();
        #endif
      }

      public BookingMatchResults recv_matchAndFilterBooking()
      {
        TMessage msg = iprot_.ReadMessageBegin();
        if (msg.Type == TMessageType.Exception) {
          TApplicationException x = TApplicationException.Read(iprot_);
          iprot_.ReadMessageEnd();
          throw x;
        }
        matchAndFilterBooking_result result = new matchAndFilterBooking_result();
        result.Read(iprot_);
        iprot_.ReadMessageEnd();
        if (result.__isset.success) {
          return result.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "matchAndFilterBooking failed: unknown result");
      }

      
      #if SILVERLIGHT
      public IAsyncResult Begin_fetchResults(AsyncCallback callback, object state, int id, int count)
      {
        return send_fetchResults(callback, state, id, count);
      }

      public List<PooledBooking> End_fetchResults(IAsyncResult asyncResult)
      {
        oprot_.Transport.EndFlush(asyncResult);
        return recv_fetchResults();
      }

      #endif

      public List<PooledBooking> fetchResults(int id, int count)
      {
        #if !SILVERLIGHT
        send_fetchResults(id, count);
        return recv_fetchResults();

        #else
        var asyncResult = Begin_fetchResults(null, null, id, count);
        return End_fetchResults(asyncResult);

        #endif
      }
      #if SILVERLIGHT
      public IAsyncResult send_fetchResults(AsyncCallback callback, object state, int id, int count)
      #else
      public void send_fetchResults(int id, int count)
      #endif
      {
        oprot_.WriteMessageBegin(new TMessage("fetchResults", TMessageType.Call, seqid_));
        fetchResults_args args = new fetchResults_args();
        args.Id = id;
        args.Count = count;
        args.Write(oprot_);
        oprot_.WriteMessageEnd();
        #if SILVERLIGHT
        return oprot_.Transport.BeginFlush(callback, state);
        #else
        oprot_.Transport.Flush();
        #endif
      }

      public List<PooledBooking> recv_fetchResults()
      {
        TMessage msg = iprot_.ReadMessageBegin();
        if (msg.Type == TMessageType.Exception) {
          TApplicationException x = TApplicationException.Read(iprot_);
          iprot_.ReadMessageEnd();
          throw x;
        }
        fetchResults_result result = new fetchResults_result();
        result.Read(iprot_);
        iprot_.ReadMessageEnd();
        if (result.__isset.success) {
          return result.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "fetchResults failed: unknown result");
      }

      
      #if SILVERLIGHT
      public IAsyncResult Begin_cancel(AsyncCallback callback, object state, long bookingId)
      {
        return send_cancel(callback, state, bookingId);
      }

      public bool End_cancel(IAsyncResult asyncResult)
      {
        oprot_.Transport.EndFlush(asyncResult);
        return recv_cancel();
      }

      #endif

      public bool cancel(long bookingId)
      {
        #if !SILVERLIGHT
        send_cancel(bookingId);
        return recv_cancel();

        #else
        var asyncResult = Begin_cancel(null, null, bookingId);
        return End_cancel(asyncResult);

        #endif
      }
      #if SILVERLIGHT
      public IAsyncResult send_cancel(AsyncCallback callback, object state, long bookingId)
      #else
      public void send_cancel(long bookingId)
      #endif
      {
        oprot_.WriteMessageBegin(new TMessage("cancel", TMessageType.Call, seqid_));
        cancel_args args = new cancel_args();
        args.BookingId = bookingId;
        args.Write(oprot_);
        oprot_.WriteMessageEnd();
        #if SILVERLIGHT
        return oprot_.Transport.BeginFlush(callback, state);
        #else
        oprot_.Transport.Flush();
        #endif
      }

      public bool recv_cancel()
      {
        TMessage msg = iprot_.ReadMessageBegin();
        if (msg.Type == TMessageType.Exception) {
          TApplicationException x = TApplicationException.Read(iprot_);
          iprot_.ReadMessageEnd();
          throw x;
        }
        cancel_result result = new cancel_result();
        result.Read(iprot_);
        iprot_.ReadMessageEnd();
        if (result.__isset.success) {
          return result.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "cancel failed: unknown result");
      }

    }
    public class Processor : TProcessor {
      public Processor(Iface iface)
      {
        iface_ = iface;
        processMap_["submitBooking"] = submitBooking_Process;
        processMap_["matchBooking"] = matchBooking_Process;
        processMap_["matchAndFilterBooking"] = matchAndFilterBooking_Process;
        processMap_["fetchResults"] = fetchResults_Process;
        processMap_["cancel"] = cancel_Process;
      }

      protected delegate void ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot);
      private Iface iface_;
      protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

      public bool Process(TProtocol iprot, TProtocol oprot)
      {
        try
        {
          TMessage msg = iprot.ReadMessageBegin();
          ProcessFunction fn;
          processMap_.TryGetValue(msg.Name, out fn);
          if (fn == null) {
            TProtocolUtil.Skip(iprot, TType.Struct);
            iprot.ReadMessageEnd();
            TApplicationException x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
            oprot.WriteMessageBegin(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID));
            x.Write(oprot);
            oprot.WriteMessageEnd();
            oprot.Transport.Flush();
            return true;
          }
          fn(msg.SeqID, iprot, oprot);
        }
        catch (IOException)
        {
          return false;
        }
        return true;
      }

      public void submitBooking_Process(int seqid, TProtocol iprot, TProtocol oprot)
      {
        submitBooking_args args = new submitBooking_args();
        args.Read(iprot);
        iprot.ReadMessageEnd();
        submitBooking_result result = new submitBooking_result();
        try {
          result.Success = iface_.submitBooking(args.BookingParams);
        } catch (SavariWala.ServerError err) {
          result.Err = err;
        }
        oprot.WriteMessageBegin(new TMessage("submitBooking", TMessageType.Reply, seqid)); 
        result.Write(oprot);
        oprot.WriteMessageEnd();
        oprot.Transport.Flush();
      }

      public void matchBooking_Process(int seqid, TProtocol iprot, TProtocol oprot)
      {
        matchBooking_args args = new matchBooking_args();
        args.Read(iprot);
        iprot.ReadMessageEnd();
        matchBooking_result result = new matchBooking_result();
        result.Success = iface_.matchBooking(args.Src);
        oprot.WriteMessageBegin(new TMessage("matchBooking", TMessageType.Reply, seqid)); 
        result.Write(oprot);
        oprot.WriteMessageEnd();
        oprot.Transport.Flush();
      }

      public void matchAndFilterBooking_Process(int seqid, TProtocol iprot, TProtocol oprot)
      {
        matchAndFilterBooking_args args = new matchAndFilterBooking_args();
        args.Read(iprot);
        iprot.ReadMessageEnd();
        matchAndFilterBooking_result result = new matchAndFilterBooking_result();
        result.Success = iface_.matchAndFilterBooking(args.Src, args.Dst);
        oprot.WriteMessageBegin(new TMessage("matchAndFilterBooking", TMessageType.Reply, seqid)); 
        result.Write(oprot);
        oprot.WriteMessageEnd();
        oprot.Transport.Flush();
      }

      public void fetchResults_Process(int seqid, TProtocol iprot, TProtocol oprot)
      {
        fetchResults_args args = new fetchResults_args();
        args.Read(iprot);
        iprot.ReadMessageEnd();
        fetchResults_result result = new fetchResults_result();
        result.Success = iface_.fetchResults(args.Id, args.Count);
        oprot.WriteMessageBegin(new TMessage("fetchResults", TMessageType.Reply, seqid)); 
        result.Write(oprot);
        oprot.WriteMessageEnd();
        oprot.Transport.Flush();
      }

      public void cancel_Process(int seqid, TProtocol iprot, TProtocol oprot)
      {
        cancel_args args = new cancel_args();
        args.Read(iprot);
        iprot.ReadMessageEnd();
        cancel_result result = new cancel_result();
        result.Success = iface_.cancel(args.BookingId);
        oprot.WriteMessageBegin(new TMessage("cancel", TMessageType.Reply, seqid)); 
        result.Write(oprot);
        oprot.WriteMessageEnd();
        oprot.Transport.Flush();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class submitBooking_args : TBase
    {
      private BookingParams _bookingParams;

      public BookingParams BookingParams
      {
        get
        {
          return _bookingParams;
        }
        set
        {
          __isset.bookingParams = true;
          this._bookingParams = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool bookingParams;
      }

      public submitBooking_args() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                BookingParams = new BookingParams();
                BookingParams.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("submitBooking_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (BookingParams != null && __isset.bookingParams) {
          field.Name = "bookingParams";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          BookingParams.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("submitBooking_args(");
        sb.Append("BookingParams: ");
        sb.Append(BookingParams== null ? "<null>" : BookingParams.ToString());
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class submitBooking_result : TBase
    {
      private long _success;
      private SavariWala.ServerError _err;

      public long Success
      {
        get
        {
          return _success;
        }
        set
        {
          __isset.success = true;
          this._success = value;
        }
      }

      public SavariWala.ServerError Err
      {
        get
        {
          return _err;
        }
        set
        {
          __isset.err = true;
          this._err = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool success;
        public bool err;
      }

      public submitBooking_result() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.I64) {
                Success = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 1:
              if (field.Type == TType.Struct) {
                Err = new SavariWala.ServerError();
                Err.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("submitBooking_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          field.Name = "Success";
          field.Type = TType.I64;
          field.ID = 0;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(Success);
          oprot.WriteFieldEnd();
        } else if (this.__isset.err) {
          if (Err != null) {
            field.Name = "Err";
            field.Type = TType.Struct;
            field.ID = 1;
            oprot.WriteFieldBegin(field);
            Err.Write(oprot);
            oprot.WriteFieldEnd();
          }
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("submitBooking_result(");
        sb.Append("Success: ");
        sb.Append(Success);
        sb.Append(",Err: ");
        sb.Append(Err== null ? "<null>" : Err.ToString());
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class matchBooking_args : TBase
    {
      private SavariWala.GeoLoc _src;

      public SavariWala.GeoLoc Src
      {
        get
        {
          return _src;
        }
        set
        {
          __isset.src = true;
          this._src = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool src;
      }

      public matchBooking_args() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                Src = new SavariWala.GeoLoc();
                Src.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("matchBooking_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Src != null && __isset.src) {
          field.Name = "src";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Src.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("matchBooking_args(");
        sb.Append("Src: ");
        sb.Append(Src== null ? "<null>" : Src.ToString());
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class matchBooking_result : TBase
    {
      private BookingMatchResults _success;

      public BookingMatchResults Success
      {
        get
        {
          return _success;
        }
        set
        {
          __isset.success = true;
          this._success = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool success;
      }

      public matchBooking_result() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.Struct) {
                Success = new BookingMatchResults();
                Success.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("matchBooking_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          if (Success != null) {
            field.Name = "Success";
            field.Type = TType.Struct;
            field.ID = 0;
            oprot.WriteFieldBegin(field);
            Success.Write(oprot);
            oprot.WriteFieldEnd();
          }
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("matchBooking_result(");
        sb.Append("Success: ");
        sb.Append(Success== null ? "<null>" : Success.ToString());
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class matchAndFilterBooking_args : TBase
    {
      private SavariWala.GeoLoc _src;
      private SavariWala.GeoLoc _dst;

      public SavariWala.GeoLoc Src
      {
        get
        {
          return _src;
        }
        set
        {
          __isset.src = true;
          this._src = value;
        }
      }

      public SavariWala.GeoLoc Dst
      {
        get
        {
          return _dst;
        }
        set
        {
          __isset.dst = true;
          this._dst = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool src;
        public bool dst;
      }

      public matchAndFilterBooking_args() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                Src = new SavariWala.GeoLoc();
                Src.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Struct) {
                Dst = new SavariWala.GeoLoc();
                Dst.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("matchAndFilterBooking_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Src != null && __isset.src) {
          field.Name = "src";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Src.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Dst != null && __isset.dst) {
          field.Name = "dst";
          field.Type = TType.Struct;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          Dst.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("matchAndFilterBooking_args(");
        sb.Append("Src: ");
        sb.Append(Src== null ? "<null>" : Src.ToString());
        sb.Append(",Dst: ");
        sb.Append(Dst== null ? "<null>" : Dst.ToString());
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class matchAndFilterBooking_result : TBase
    {
      private BookingMatchResults _success;

      public BookingMatchResults Success
      {
        get
        {
          return _success;
        }
        set
        {
          __isset.success = true;
          this._success = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool success;
      }

      public matchAndFilterBooking_result() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.Struct) {
                Success = new BookingMatchResults();
                Success.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("matchAndFilterBooking_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          if (Success != null) {
            field.Name = "Success";
            field.Type = TType.Struct;
            field.ID = 0;
            oprot.WriteFieldBegin(field);
            Success.Write(oprot);
            oprot.WriteFieldEnd();
          }
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("matchAndFilterBooking_result(");
        sb.Append("Success: ");
        sb.Append(Success== null ? "<null>" : Success.ToString());
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class fetchResults_args : TBase
    {
      private int _id;
      private int _count;

      public int Id
      {
        get
        {
          return _id;
        }
        set
        {
          __isset.id = true;
          this._id = value;
        }
      }

      public int Count
      {
        get
        {
          return _count;
        }
        set
        {
          __isset.count = true;
          this._count = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool id;
        public bool count;
      }

      public fetchResults_args() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                Id = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                Count = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("fetchResults_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.id) {
          field.Name = "id";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Id);
          oprot.WriteFieldEnd();
        }
        if (__isset.count) {
          field.Name = "count";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Count);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("fetchResults_args(");
        sb.Append("Id: ");
        sb.Append(Id);
        sb.Append(",Count: ");
        sb.Append(Count);
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class fetchResults_result : TBase
    {
      private List<PooledBooking> _success;

      public List<PooledBooking> Success
      {
        get
        {
          return _success;
        }
        set
        {
          __isset.success = true;
          this._success = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool success;
      }

      public fetchResults_result() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.List) {
                {
                  Success = new List<PooledBooking>();
                  TList _list4 = iprot.ReadListBegin();
                  for( int _i5 = 0; _i5 < _list4.Count; ++_i5)
                  {
                    PooledBooking _elem6 = new PooledBooking();
                    _elem6 = new PooledBooking();
                    _elem6.Read(iprot);
                    Success.Add(_elem6);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("fetchResults_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          if (Success != null) {
            field.Name = "Success";
            field.Type = TType.List;
            field.ID = 0;
            oprot.WriteFieldBegin(field);
            {
              oprot.WriteListBegin(new TList(TType.Struct, Success.Count));
              foreach (PooledBooking _iter7 in Success)
              {
                _iter7.Write(oprot);
              }
              oprot.WriteListEnd();
            }
            oprot.WriteFieldEnd();
          }
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("fetchResults_result(");
        sb.Append("Success: ");
        sb.Append(Success);
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class cancel_args : TBase
    {
      private long _bookingId;

      public long BookingId
      {
        get
        {
          return _bookingId;
        }
        set
        {
          __isset.bookingId = true;
          this._bookingId = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool bookingId;
      }

      public cancel_args() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I64) {
                BookingId = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("cancel_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.bookingId) {
          field.Name = "bookingId";
          field.Type = TType.I64;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(BookingId);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("cancel_args(");
        sb.Append("BookingId: ");
        sb.Append(BookingId);
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class cancel_result : TBase
    {
      private bool _success;

      public bool Success
      {
        get
        {
          return _success;
        }
        set
        {
          __isset.success = true;
          this._success = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool success;
      }

      public cancel_result() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.Bool) {
                Success = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("cancel_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          field.Name = "Success";
          field.Type = TType.Bool;
          field.ID = 0;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(Success);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("cancel_result(");
        sb.Append("Success: ");
        sb.Append(Success);
        sb.Append(")");
        return sb.ToString();
      }

    }

  }
}
