/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.savariwala;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class BookingParams implements org.apache.thrift.TBase<BookingParams, BookingParams._Fields>, java.io.Serializable, Cloneable, Comparable<BookingParams> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BookingParams");

  private static final org.apache.thrift.protocol.TField NUM_PAX_FIELD_DESC = new org.apache.thrift.protocol.TField("numPax", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField START_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("startTime", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField IS_SHARED_FIELD_DESC = new org.apache.thrift.protocol.TField("isShared", org.apache.thrift.protocol.TType.BOOL, (short)3);
  private static final org.apache.thrift.protocol.TField ROUTE_JSON_FIELD_DESC = new org.apache.thrift.protocol.TField("routeJson", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BookingParamsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BookingParamsTupleSchemeFactory());
  }

  public int numPax; // required
  public long startTime; // required
  public boolean isShared; // required
  public String routeJson; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NUM_PAX((short)1, "numPax"),
    START_TIME((short)2, "startTime"),
    IS_SHARED((short)3, "isShared"),
    ROUTE_JSON((short)4, "routeJson");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NUM_PAX
          return NUM_PAX;
        case 2: // START_TIME
          return START_TIME;
        case 3: // IS_SHARED
          return IS_SHARED;
        case 4: // ROUTE_JSON
          return ROUTE_JSON;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NUMPAX_ISSET_ID = 0;
  private static final int __STARTTIME_ISSET_ID = 1;
  private static final int __ISSHARED_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NUM_PAX, new org.apache.thrift.meta_data.FieldMetaData("numPax", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.START_TIME, new org.apache.thrift.meta_data.FieldMetaData("startTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.IS_SHARED, new org.apache.thrift.meta_data.FieldMetaData("isShared", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ROUTE_JSON, new org.apache.thrift.meta_data.FieldMetaData("routeJson", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BookingParams.class, metaDataMap);
  }

  public BookingParams() {
  }

  public BookingParams(
    int numPax,
    long startTime,
    boolean isShared,
    String routeJson)
  {
    this();
    this.numPax = numPax;
    setNumPaxIsSet(true);
    this.startTime = startTime;
    setStartTimeIsSet(true);
    this.isShared = isShared;
    setIsSharedIsSet(true);
    this.routeJson = routeJson;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BookingParams(BookingParams other) {
    __isset_bitfield = other.__isset_bitfield;
    this.numPax = other.numPax;
    this.startTime = other.startTime;
    this.isShared = other.isShared;
    if (other.isSetRouteJson()) {
      this.routeJson = other.routeJson;
    }
  }

  public BookingParams deepCopy() {
    return new BookingParams(this);
  }

  @Override
  public void clear() {
    setNumPaxIsSet(false);
    this.numPax = 0;
    setStartTimeIsSet(false);
    this.startTime = 0;
    setIsSharedIsSet(false);
    this.isShared = false;
    this.routeJson = null;
  }

  public int getNumPax() {
    return this.numPax;
  }

  public BookingParams setNumPax(int numPax) {
    this.numPax = numPax;
    setNumPaxIsSet(true);
    return this;
  }

  public void unsetNumPax() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NUMPAX_ISSET_ID);
  }

  /** Returns true if field numPax is set (has been assigned a value) and false otherwise */
  public boolean isSetNumPax() {
    return EncodingUtils.testBit(__isset_bitfield, __NUMPAX_ISSET_ID);
  }

  public void setNumPaxIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NUMPAX_ISSET_ID, value);
  }

  public long getStartTime() {
    return this.startTime;
  }

  public BookingParams setStartTime(long startTime) {
    this.startTime = startTime;
    setStartTimeIsSet(true);
    return this;
  }

  public void unsetStartTime() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __STARTTIME_ISSET_ID);
  }

  /** Returns true if field startTime is set (has been assigned a value) and false otherwise */
  public boolean isSetStartTime() {
    return EncodingUtils.testBit(__isset_bitfield, __STARTTIME_ISSET_ID);
  }

  public void setStartTimeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __STARTTIME_ISSET_ID, value);
  }

  public boolean isIsShared() {
    return this.isShared;
  }

  public BookingParams setIsShared(boolean isShared) {
    this.isShared = isShared;
    setIsSharedIsSet(true);
    return this;
  }

  public void unsetIsShared() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ISSHARED_ISSET_ID);
  }

  /** Returns true if field isShared is set (has been assigned a value) and false otherwise */
  public boolean isSetIsShared() {
    return EncodingUtils.testBit(__isset_bitfield, __ISSHARED_ISSET_ID);
  }

  public void setIsSharedIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ISSHARED_ISSET_ID, value);
  }

  public String getRouteJson() {
    return this.routeJson;
  }

  public BookingParams setRouteJson(String routeJson) {
    this.routeJson = routeJson;
    return this;
  }

  public void unsetRouteJson() {
    this.routeJson = null;
  }

  /** Returns true if field routeJson is set (has been assigned a value) and false otherwise */
  public boolean isSetRouteJson() {
    return this.routeJson != null;
  }

  public void setRouteJsonIsSet(boolean value) {
    if (!value) {
      this.routeJson = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NUM_PAX:
      if (value == null) {
        unsetNumPax();
      } else {
        setNumPax((Integer)value);
      }
      break;

    case START_TIME:
      if (value == null) {
        unsetStartTime();
      } else {
        setStartTime((Long)value);
      }
      break;

    case IS_SHARED:
      if (value == null) {
        unsetIsShared();
      } else {
        setIsShared((Boolean)value);
      }
      break;

    case ROUTE_JSON:
      if (value == null) {
        unsetRouteJson();
      } else {
        setRouteJson((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NUM_PAX:
      return Integer.valueOf(getNumPax());

    case START_TIME:
      return Long.valueOf(getStartTime());

    case IS_SHARED:
      return Boolean.valueOf(isIsShared());

    case ROUTE_JSON:
      return getRouteJson();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NUM_PAX:
      return isSetNumPax();
    case START_TIME:
      return isSetStartTime();
    case IS_SHARED:
      return isSetIsShared();
    case ROUTE_JSON:
      return isSetRouteJson();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof BookingParams)
      return this.equals((BookingParams)that);
    return false;
  }

  public boolean equals(BookingParams that) {
    if (that == null)
      return false;

    boolean this_present_numPax = true;
    boolean that_present_numPax = true;
    if (this_present_numPax || that_present_numPax) {
      if (!(this_present_numPax && that_present_numPax))
        return false;
      if (this.numPax != that.numPax)
        return false;
    }

    boolean this_present_startTime = true;
    boolean that_present_startTime = true;
    if (this_present_startTime || that_present_startTime) {
      if (!(this_present_startTime && that_present_startTime))
        return false;
      if (this.startTime != that.startTime)
        return false;
    }

    boolean this_present_isShared = true;
    boolean that_present_isShared = true;
    if (this_present_isShared || that_present_isShared) {
      if (!(this_present_isShared && that_present_isShared))
        return false;
      if (this.isShared != that.isShared)
        return false;
    }

    boolean this_present_routeJson = true && this.isSetRouteJson();
    boolean that_present_routeJson = true && that.isSetRouteJson();
    if (this_present_routeJson || that_present_routeJson) {
      if (!(this_present_routeJson && that_present_routeJson))
        return false;
      if (!this.routeJson.equals(that.routeJson))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(BookingParams other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetNumPax()).compareTo(other.isSetNumPax());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumPax()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.numPax, other.numPax);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStartTime()).compareTo(other.isSetStartTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStartTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.startTime, other.startTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIsShared()).compareTo(other.isSetIsShared());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsShared()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isShared, other.isShared);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRouteJson()).compareTo(other.isSetRouteJson());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRouteJson()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.routeJson, other.routeJson);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("BookingParams(");
    boolean first = true;

    sb.append("numPax:");
    sb.append(this.numPax);
    first = false;
    if (!first) sb.append(", ");
    sb.append("startTime:");
    sb.append(this.startTime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("isShared:");
    sb.append(this.isShared);
    first = false;
    if (!first) sb.append(", ");
    sb.append("routeJson:");
    if (this.routeJson == null) {
      sb.append("null");
    } else {
      sb.append(this.routeJson);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BookingParamsStandardSchemeFactory implements SchemeFactory {
    public BookingParamsStandardScheme getScheme() {
      return new BookingParamsStandardScheme();
    }
  }

  private static class BookingParamsStandardScheme extends StandardScheme<BookingParams> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BookingParams struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NUM_PAX
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.numPax = iprot.readI32();
              struct.setNumPaxIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // START_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.startTime = iprot.readI64();
              struct.setStartTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // IS_SHARED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isShared = iprot.readBool();
              struct.setIsSharedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ROUTE_JSON
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.routeJson = iprot.readString();
              struct.setRouteJsonIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BookingParams struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(NUM_PAX_FIELD_DESC);
      oprot.writeI32(struct.numPax);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(START_TIME_FIELD_DESC);
      oprot.writeI64(struct.startTime);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(IS_SHARED_FIELD_DESC);
      oprot.writeBool(struct.isShared);
      oprot.writeFieldEnd();
      if (struct.routeJson != null) {
        oprot.writeFieldBegin(ROUTE_JSON_FIELD_DESC);
        oprot.writeString(struct.routeJson);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BookingParamsTupleSchemeFactory implements SchemeFactory {
    public BookingParamsTupleScheme getScheme() {
      return new BookingParamsTupleScheme();
    }
  }

  private static class BookingParamsTupleScheme extends TupleScheme<BookingParams> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BookingParams struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetNumPax()) {
        optionals.set(0);
      }
      if (struct.isSetStartTime()) {
        optionals.set(1);
      }
      if (struct.isSetIsShared()) {
        optionals.set(2);
      }
      if (struct.isSetRouteJson()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetNumPax()) {
        oprot.writeI32(struct.numPax);
      }
      if (struct.isSetStartTime()) {
        oprot.writeI64(struct.startTime);
      }
      if (struct.isSetIsShared()) {
        oprot.writeBool(struct.isShared);
      }
      if (struct.isSetRouteJson()) {
        oprot.writeString(struct.routeJson);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BookingParams struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.numPax = iprot.readI32();
        struct.setNumPaxIsSet(true);
      }
      if (incoming.get(1)) {
        struct.startTime = iprot.readI64();
        struct.setStartTimeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.isShared = iprot.readBool();
        struct.setIsSharedIsSet(true);
      }
      if (incoming.get(3)) {
        struct.routeJson = iprot.readString();
        struct.setRouteJsonIsSet(true);
      }
    }
  }

}

