/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.savariwala;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MapPointProvider {

  public interface Iface {

    public List<com.savariwala.MapPoint> getMapPoint(boolean isSrc, com.savariwala.GeoLoc loc) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void getMapPoint(boolean isSrc, com.savariwala.GeoLoc loc, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public List<com.savariwala.MapPoint> getMapPoint(boolean isSrc, com.savariwala.GeoLoc loc) throws org.apache.thrift.TException
    {
      send_getMapPoint(isSrc, loc);
      return recv_getMapPoint();
    }

    public void send_getMapPoint(boolean isSrc, com.savariwala.GeoLoc loc) throws org.apache.thrift.TException
    {
      getMapPoint_args args = new getMapPoint_args();
      args.setIsSrc(isSrc);
      args.setLoc(loc);
      sendBase("getMapPoint", args);
    }

    public List<com.savariwala.MapPoint> recv_getMapPoint() throws org.apache.thrift.TException
    {
      getMapPoint_result result = new getMapPoint_result();
      receiveBase(result, "getMapPoint");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "getMapPoint failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void getMapPoint(boolean isSrc, com.savariwala.GeoLoc loc, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException {
      checkReady();
      getMapPoint_call method_call = new getMapPoint_call(isSrc, loc, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class getMapPoint_call extends org.apache.thrift.async.TAsyncMethodCall {
      private boolean isSrc;
      private com.savariwala.GeoLoc loc;
      public getMapPoint_call(boolean isSrc, com.savariwala.GeoLoc loc, org.apache.thrift.async.AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.isSrc = isSrc;
        this.loc = loc;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("getMapPoint", org.apache.thrift.protocol.TMessageType.CALL, 0));
        getMapPoint_args args = new getMapPoint_args();
        args.setIsSrc(isSrc);
        args.setLoc(loc);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public List<com.savariwala.MapPoint> getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_getMapPoint();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("getMapPoint", new getMapPoint());
      return processMap;
    }

    public static class getMapPoint<I extends Iface> extends org.apache.thrift.ProcessFunction<I, getMapPoint_args> {
      public getMapPoint() {
        super("getMapPoint");
      }

      public getMapPoint_args getEmptyArgsInstance() {
        return new getMapPoint_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public getMapPoint_result getResult(I iface, getMapPoint_args args) throws org.apache.thrift.TException {
        getMapPoint_result result = new getMapPoint_result();
        result.success = iface.getMapPoint(args.isSrc, args.loc);
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final Logger LOGGER = LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("getMapPoint", new getMapPoint());
      return processMap;
    }

    public static class getMapPoint<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, getMapPoint_args, List<com.savariwala.MapPoint>> {
      public getMapPoint() {
        super("getMapPoint");
      }

      public getMapPoint_args getEmptyArgsInstance() {
        return new getMapPoint_args();
      }

      public AsyncMethodCallback<List<com.savariwala.MapPoint>> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<List<com.savariwala.MapPoint>>() { 
          public void onComplete(List<com.savariwala.MapPoint> o) {
            getMapPoint_result result = new getMapPoint_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            getMapPoint_result result = new getMapPoint_result();
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, getMapPoint_args args, org.apache.thrift.async.AsyncMethodCallback<List<com.savariwala.MapPoint>> resultHandler) throws TException {
        iface.getMapPoint(args.isSrc, args.loc,resultHandler);
      }
    }

  }

  public static class getMapPoint_args implements org.apache.thrift.TBase<getMapPoint_args, getMapPoint_args._Fields>, java.io.Serializable, Cloneable, Comparable<getMapPoint_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getMapPoint_args");

    private static final org.apache.thrift.protocol.TField IS_SRC_FIELD_DESC = new org.apache.thrift.protocol.TField("isSrc", org.apache.thrift.protocol.TType.BOOL, (short)1);
    private static final org.apache.thrift.protocol.TField LOC_FIELD_DESC = new org.apache.thrift.protocol.TField("loc", org.apache.thrift.protocol.TType.STRUCT, (short)2);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new getMapPoint_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new getMapPoint_argsTupleSchemeFactory());
    }

    public boolean isSrc; // required
    public com.savariwala.GeoLoc loc; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      IS_SRC((short)1, "isSrc"),
      LOC((short)2, "loc");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // IS_SRC
            return IS_SRC;
          case 2: // LOC
            return LOC;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __ISSRC_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.IS_SRC, new org.apache.thrift.meta_data.FieldMetaData("isSrc", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
      tmpMap.put(_Fields.LOC, new org.apache.thrift.meta_data.FieldMetaData("loc", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.savariwala.GeoLoc.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getMapPoint_args.class, metaDataMap);
    }

    public getMapPoint_args() {
    }

    public getMapPoint_args(
      boolean isSrc,
      com.savariwala.GeoLoc loc)
    {
      this();
      this.isSrc = isSrc;
      setIsSrcIsSet(true);
      this.loc = loc;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getMapPoint_args(getMapPoint_args other) {
      __isset_bitfield = other.__isset_bitfield;
      this.isSrc = other.isSrc;
      if (other.isSetLoc()) {
        this.loc = new com.savariwala.GeoLoc(other.loc);
      }
    }

    public getMapPoint_args deepCopy() {
      return new getMapPoint_args(this);
    }

    @Override
    public void clear() {
      setIsSrcIsSet(false);
      this.isSrc = false;
      this.loc = null;
    }

    public boolean isIsSrc() {
      return this.isSrc;
    }

    public getMapPoint_args setIsSrc(boolean isSrc) {
      this.isSrc = isSrc;
      setIsSrcIsSet(true);
      return this;
    }

    public void unsetIsSrc() {
      __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ISSRC_ISSET_ID);
    }

    /** Returns true if field isSrc is set (has been assigned a value) and false otherwise */
    public boolean isSetIsSrc() {
      return EncodingUtils.testBit(__isset_bitfield, __ISSRC_ISSET_ID);
    }

    public void setIsSrcIsSet(boolean value) {
      __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ISSRC_ISSET_ID, value);
    }

    public com.savariwala.GeoLoc getLoc() {
      return this.loc;
    }

    public getMapPoint_args setLoc(com.savariwala.GeoLoc loc) {
      this.loc = loc;
      return this;
    }

    public void unsetLoc() {
      this.loc = null;
    }

    /** Returns true if field loc is set (has been assigned a value) and false otherwise */
    public boolean isSetLoc() {
      return this.loc != null;
    }

    public void setLocIsSet(boolean value) {
      if (!value) {
        this.loc = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case IS_SRC:
        if (value == null) {
          unsetIsSrc();
        } else {
          setIsSrc((Boolean)value);
        }
        break;

      case LOC:
        if (value == null) {
          unsetLoc();
        } else {
          setLoc((com.savariwala.GeoLoc)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case IS_SRC:
        return Boolean.valueOf(isIsSrc());

      case LOC:
        return getLoc();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case IS_SRC:
        return isSetIsSrc();
      case LOC:
        return isSetLoc();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getMapPoint_args)
        return this.equals((getMapPoint_args)that);
      return false;
    }

    public boolean equals(getMapPoint_args that) {
      if (that == null)
        return false;

      boolean this_present_isSrc = true;
      boolean that_present_isSrc = true;
      if (this_present_isSrc || that_present_isSrc) {
        if (!(this_present_isSrc && that_present_isSrc))
          return false;
        if (this.isSrc != that.isSrc)
          return false;
      }

      boolean this_present_loc = true && this.isSetLoc();
      boolean that_present_loc = true && that.isSetLoc();
      if (this_present_loc || that_present_loc) {
        if (!(this_present_loc && that_present_loc))
          return false;
        if (!this.loc.equals(that.loc))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    @Override
    public int compareTo(getMapPoint_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetIsSrc()).compareTo(other.isSetIsSrc());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetIsSrc()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isSrc, other.isSrc);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetLoc()).compareTo(other.isSetLoc());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetLoc()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.loc, other.loc);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getMapPoint_args(");
      boolean first = true;

      sb.append("isSrc:");
      sb.append(this.isSrc);
      first = false;
      if (!first) sb.append(", ");
      sb.append("loc:");
      if (this.loc == null) {
        sb.append("null");
      } else {
        sb.append(this.loc);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (loc != null) {
        loc.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bitfield = 0;
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getMapPoint_argsStandardSchemeFactory implements SchemeFactory {
      public getMapPoint_argsStandardScheme getScheme() {
        return new getMapPoint_argsStandardScheme();
      }
    }

    private static class getMapPoint_argsStandardScheme extends StandardScheme<getMapPoint_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getMapPoint_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // IS_SRC
              if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
                struct.isSrc = iprot.readBool();
                struct.setIsSrcIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // LOC
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.loc = new com.savariwala.GeoLoc();
                struct.loc.read(iprot);
                struct.setLocIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getMapPoint_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        oprot.writeFieldBegin(IS_SRC_FIELD_DESC);
        oprot.writeBool(struct.isSrc);
        oprot.writeFieldEnd();
        if (struct.loc != null) {
          oprot.writeFieldBegin(LOC_FIELD_DESC);
          struct.loc.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getMapPoint_argsTupleSchemeFactory implements SchemeFactory {
      public getMapPoint_argsTupleScheme getScheme() {
        return new getMapPoint_argsTupleScheme();
      }
    }

    private static class getMapPoint_argsTupleScheme extends TupleScheme<getMapPoint_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getMapPoint_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetIsSrc()) {
          optionals.set(0);
        }
        if (struct.isSetLoc()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetIsSrc()) {
          oprot.writeBool(struct.isSrc);
        }
        if (struct.isSetLoc()) {
          struct.loc.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getMapPoint_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.isSrc = iprot.readBool();
          struct.setIsSrcIsSet(true);
        }
        if (incoming.get(1)) {
          struct.loc = new com.savariwala.GeoLoc();
          struct.loc.read(iprot);
          struct.setLocIsSet(true);
        }
      }
    }

  }

  public static class getMapPoint_result implements org.apache.thrift.TBase<getMapPoint_result, getMapPoint_result._Fields>, java.io.Serializable, Cloneable, Comparable<getMapPoint_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getMapPoint_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.LIST, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new getMapPoint_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new getMapPoint_resultTupleSchemeFactory());
    }

    public List<com.savariwala.MapPoint> success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
              new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.savariwala.MapPoint.class))));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getMapPoint_result.class, metaDataMap);
    }

    public getMapPoint_result() {
    }

    public getMapPoint_result(
      List<com.savariwala.MapPoint> success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getMapPoint_result(getMapPoint_result other) {
      if (other.isSetSuccess()) {
        List<com.savariwala.MapPoint> __this__success = new ArrayList<com.savariwala.MapPoint>(other.success.size());
        for (com.savariwala.MapPoint other_element : other.success) {
          __this__success.add(new com.savariwala.MapPoint(other_element));
        }
        this.success = __this__success;
      }
    }

    public getMapPoint_result deepCopy() {
      return new getMapPoint_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public int getSuccessSize() {
      return (this.success == null) ? 0 : this.success.size();
    }

    public java.util.Iterator<com.savariwala.MapPoint> getSuccessIterator() {
      return (this.success == null) ? null : this.success.iterator();
    }

    public void addToSuccess(com.savariwala.MapPoint elem) {
      if (this.success == null) {
        this.success = new ArrayList<com.savariwala.MapPoint>();
      }
      this.success.add(elem);
    }

    public List<com.savariwala.MapPoint> getSuccess() {
      return this.success;
    }

    public getMapPoint_result setSuccess(List<com.savariwala.MapPoint> success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((List<com.savariwala.MapPoint>)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getMapPoint_result)
        return this.equals((getMapPoint_result)that);
      return false;
    }

    public boolean equals(getMapPoint_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    @Override
    public int compareTo(getMapPoint_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getMapPoint_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getMapPoint_resultStandardSchemeFactory implements SchemeFactory {
      public getMapPoint_resultStandardScheme getScheme() {
        return new getMapPoint_resultStandardScheme();
      }
    }

    private static class getMapPoint_resultStandardScheme extends StandardScheme<getMapPoint_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getMapPoint_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                  struct.success = new ArrayList<com.savariwala.MapPoint>(_list0.size);
                  for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                  {
                    com.savariwala.MapPoint _elem2;
                    _elem2 = new com.savariwala.MapPoint();
                    _elem2.read(iprot);
                    struct.success.add(_elem2);
                  }
                  iprot.readListEnd();
                }
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getMapPoint_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.success.size()));
            for (com.savariwala.MapPoint _iter3 : struct.success)
            {
              _iter3.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getMapPoint_resultTupleSchemeFactory implements SchemeFactory {
      public getMapPoint_resultTupleScheme getScheme() {
        return new getMapPoint_resultTupleScheme();
      }
    }

    private static class getMapPoint_resultTupleScheme extends TupleScheme<getMapPoint_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getMapPoint_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          {
            oprot.writeI32(struct.success.size());
            for (com.savariwala.MapPoint _iter4 : struct.success)
            {
              _iter4.write(oprot);
            }
          }
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getMapPoint_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
            struct.success = new ArrayList<com.savariwala.MapPoint>(_list5.size);
            for (int _i6 = 0; _i6 < _list5.size; ++_i6)
            {
              com.savariwala.MapPoint _elem7;
              _elem7 = new com.savariwala.MapPoint();
              _elem7.read(iprot);
              struct.success.add(_elem7);
            }
          }
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

}
