/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Exception_CONSTANTS_H
#define Exception_CONSTANTS_H

#include "Exception_types.h"

namespace savariwala {

class ExceptionConstants {
 public:
  ExceptionConstants();

};

extern const ExceptionConstants g_Exception_constants;

} // namespace

#endif
