LIB = libgensw.a

THRIFT=yes

SRCS = Exception_constants.cpp Exception_types.cpp MapPointProvider.cpp MapPointProvider_server.skeleton.cpp NearestPoint_constants.cpp NearestPoint_types.cpp User_constants.cpp User_types.cpp UsersManager.cpp UsersManager_server.skeleton.cpp 

include ../../make/Makefile.inc
