/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MapPoint_CONSTANTS_H
#define MapPoint_CONSTANTS_H

#include "MapPoint_types.h"

namespace savariwala {

class MapPointConstants {
 public:
  MapPointConstants();

};

extern const MapPointConstants g_MapPoint_constants;

} // namespace

#endif
