/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "NearestPoint_constants.h"

namespace savariwala {

const NearestPointConstants g_NearestPoint_constants;

NearestPointConstants::NearestPointConstants() {
}

} // namespace

