// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "RequestHandler.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::savariwala;

class RequestHandlerHandler : virtual public RequestHandlerIf {
 public:
  RequestHandlerHandler() {
    // Your initialization goes here
  }

  int64_t submitBooking(const  ::savariwala::MapPoint& src, const  ::savariwala::MapPoint& dst, const int32_t numPax) {
    // Your implementation goes here
    printf("submitBooking\n");
  }

  void getDetails(BookingDetails& _return, const int64_t bookingId) {
    // Your implementation goes here
    printf("getDetails\n");
  }

  bool cancel(const int64_t bookingId) {
    // Your implementation goes here
    printf("cancel\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<RequestHandlerHandler> handler(new RequestHandlerHandler());
  shared_ptr<TProcessor> processor(new RequestHandlerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

