/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RequestHandler_CONSTANTS_H
#define RequestHandler_CONSTANTS_H

#include "RequestHandler_types.h"

namespace savariwala {

class RequestHandlerConstants {
 public:
  RequestHandlerConstants();

};

extern const RequestHandlerConstants g_RequestHandler_constants;

} // namespace

#endif
